### ISSUE TITLE
quickstart fails to run

### ISSUE THREAD

**Issue by awolde** [GoogleCloudPlatform/php-docs-samples#329]
I ran storage/quickstart on compute node in Google cloud and getting errors. I put in my project id here - https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/storage/quickstart/quickstart.php#L26. Is there another place I need to enable API access or keys?
```
# php quickstart.php 
PHP Fatal error:  Uncaught Google\Cloud\Exception\ServiceException: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
 in /root/php-docs-samples/storage/quickstart/vendor/google/cloud/src/RequestWrapper.php:219
Stack trace:
#0 /root/php-docs-samples/storage/quickstart/vendor/google/cloud/src/RequestWrapper.php(136): Google\Cloud\RequestWrapper->convertToGoogleException(Object(GuzzleHttp\Exception\ClientEx
ception))
#1 /root/php-docs-samples/storage/quickstart/vendor/google/cloud/src/RestTrait.php(78): Google\Cloud\RequestWrapper->send(Object(GuzzleHttp\Psr7\Request), Array)
#2 /root/php-docs-samples/storage/quickstart/vendor/google/cloud/src/Storage/Connection/Rest.php(125): Google\Cloud\Storage\Connection\Rest->send('buckets', 'insert', Array)
#3 /root/php-docs-samples/storage/quickstart/vendor/google/cloud/src/Storage/StorageClient.php(217): Google\Cloud\Storage\Connecti in /root/php-docs-samples/storage/quickstart/vendor/g
oogle/cloud/src/RequestWrapper.php on line 219
```

**Comment by awolde** [comment]
Saw that I need to export GOOGLE_APPLICATION_CREDENTIALS variable. What if I want to embed this value in the code though?

**Comment by tmatsuo** [comment]
I think you're running the code on a Compute Engine instance. The default scope when creating a new instance is I believe read-only. Maybe you can try creating an instance with full access, or you can add storage-write for the sample to just work fine.
