### ISSUE TITLE
pubsub api sample doesn't work on windows

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#388]
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/pubsub/api/src/ProjectIdTrait.php#L27

This line seems platform specific (or bash specific?).

I'm getting the following error:

```
C:\Users\DPE Dev\work\php-docs-samples\pubsub\api>php pubsub.php topic list
The system cannot find the path specified.
PHP Fatal error:  Uncaught Error: Class 'Google\Cloud\Samples\PubSub\Exception' not found in C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\src\ProjectIdTrait.php:33
Stack trace:
#0 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\src\TopicCommand.php(82): Google\Cloud\Samples\PubSub\TopicCommand->getProjectIdFromGcloud()
#1 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\vendor\symfony\console\Command\Command.php(264): Google\Cloud\Samples\PubSub\TopicCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\vendor\symfony\console\Application.php(869): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\vendor\symfony\console\Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Google\Cloud\Samples\PubSub\TopicCommand), Obj in C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\src\ProjectIdTrait.php on line 33

Fatal error: Uncaught Error: Class 'Google\Cloud\Samples\PubSub\Exception' not found in C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\src\ProjectIdTrait.php:33
Stack trace:
#0 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\src\TopicCommand.php(82): Google\Cloud\Samples\PubSub\TopicCommand->getProjectIdFromGcloud()
#1 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\vendor\symfony\console\Command\Command.php(264): Google\Cloud\Samples\PubSub\TopicCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\vendor\symfony\console\Application.php(869): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\vendor\symfony\console\Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Google\Cloud\Samples\PubSub\TopicCommand), Obj in C:\Users\DPE Dev\work\php-docs-samples\pubsub\api\src\ProjectIdTrait.php on line 33
```

**Comment by bshaffer** [comment]
Actually I believe this is a legitimate bug, as that exception class [no longer exists](https://github.com/GoogleCloudPlatform/google-cloud-php-pubsub)

**Comment by bshaffer** [comment]
Ahh yes, the [ProjectIdTrait class](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/pubsub/api/src/ProjectIdTrait.php#L33) needs a proceeding slash

**Comment by bshaffer** [comment]
@tmatsuo please try again with the latest versions!
