### ISSUE TITLE
How to disable guzzle ssl verify?

### ISSUE THREAD

**Issue by beppe9000** [GoogleCloudPlatform/php-docs-samples#868]
I am developing on windows so the Curl backend can't find a CA database. I would like to know if there is any practical way (a static field, parameter or method i can call) to disable ssl verification.

I am using ImageAnnotatorClient but from the code it does not seem to offer a way to set guzzle settings.

**Comment by dwsupplee** [comment]
Hey @beppe9000, you can define a custom handler to execute the network request with. The following should do the trick. Let me know if it works for you!

```php
use Google\Cloud\Vision\V1\ImageAnnotatorClient;
use GuzzleHttp\Client;
use Psr\Http\Message\RequestInterface;

$guzzleClient = new Client([
    'verify' => false
]);

$client = new ImageAnnotatorClient([
    'transportConfig' => [
        'rest' => [
            'httpHandler' => function (RequestInterface $request, array $options = []) use ($guzzleClient) {
                return $guzzleClient->sendAsync($request, $options);
            }
        ]
    ]
]);
```

**Comment by beppe9000** [comment]
Oh, I see. Thanks!

**Comment by beppe9000** [comment]
I did some testing and unfortunately I get the same error as before.

Full code up to the error:

```
<?php 

require __DIR__ . '/vendor/autoload.php';

use Google\Cloud\Vision\V1\ImageAnnotatorClient;
use GuzzleHttp\Client;
use Psr\Http\Message\RequestInterface;

putenv(\Google\Auth\CredentialsLoader::ENV_VAR . '=' . __DIR__ . '\auth.json');

$guzzleClient = new Client([
    'verify' => false
]);

$client = new ImageAnnotatorClient([
    'transportConfig' => [
        'rest' => [
            'httpHandler' => function (RequestInterface $request, array $options = []) use ($guzzleClient) {
                return $guzzleClient->sendAsync($request, $options);
            }
        ]
    ]
]);

$response = $client->labelDetection(file_get_contents(__DIR__.'\img\apple.bmp'));
```

Then when I run it...

```
C:\Users\Administrator\Desktop\php-docs-samples\vision>php xTag.php

PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186
Stack trace:
#0 C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::fi in C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

```

**Comment by dwsupplee** [comment]
@beppe9000, we need to override the handler used to negotiate auth tokens as well. I should have included that in my original post, apologies. Please note that the `authHttpHandler` uses `Client::send()` vs. `Client::sendAsync()` for the `httpHandler`.

```php
use Google\ApiCore\CredentialsWrapper;
use Google\Cloud\Vision\V1\ImageAnnotatorClient;
use GuzzleHttp\Client;
use Psr\Http\Message\RequestInterface;

$guzzleClient = new Client([
    'verify' => false
]);

$client = new ImageAnnotatorClient([
    'credentials' => CredentialsWrapper::build([
        'authHttpHandler' => function (RequestInterface $request, array $options = []) use ($guzzleClient) {
            return $guzzleClient->send($request, $options);
        }
    ]),
    'transportConfig' => [
        'rest' => [
            'httpHandler' => function (RequestInterface $request, array $options = []) use ($guzzleClient) {
                return $guzzleClient->sendAsync($request, $options);
            }
        ]
    ]
]);
```

**Comment by beppe9000** [comment]
Ok, so now I get another error...

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_scope",
  "error_description": "Empty or missing scope not allowed."
}
 in C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7 in C:\Users\Administrator\Desktop\php-docs-samples\vision\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113
```

Ps. Editing the guzzle library ends up with an error about having to enable billing. I think I should be getting the same, but this one is different.

**Comment by dwsupplee** [comment]
@beppe9000 I updated [my snippet](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/868#issuecomment-483754741) to use the `credentialsConfig` key instead of passing a new `CredentialsWrapper` instance in through the `credentials` key. This approach will utilize the default scopes set on the client for you, so it is a little friendlier than having to set them yourself. Let me know if it works :)

**Comment by beppe9000** [comment]
It looks like it works now. Thanks for the help @dwsupplee !

**Comment by MANOJ-M-01** [comment]
public function index()
{
    $client  = new \GuzzleHttp\Client(['verify' =>false]); //ssl verifyication 
    $request = new \GuzzleHttp\Psr7\Request('GET', 'https://jsonplaceholder.typicode.com/posts');
    $promise = $client->sendAsync($request)->then(function ($response) {
        $sd=$response->getBody()->getContents();
        $datas=json_decode($sd);
        return response()->json($datas);
        // return view('show',compact('datas'));
    });
    return $promise->wait();
}

**Comment by alcarazolabs** [comment]
>  $client  = new \GuzzleHttp\Client(['verify' =>false]);

Thanks man! this worked for me.
